apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
spec:
  limits:
  - default:
      cpu: 900m
      memory: "1Gi"
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container