apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gene-classifier-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2023-11-10T14:52:18.024172',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "Gene Classifier"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: gene-classifier
  templates:
  - name: gene-classifier
    dag:
      tasks:
      - name: gene-classifier-model-testing
        template: gene-classifier-model-testing
        dependencies: [gene-classifier-model-training, gene-classifier-test-dataset-generation]
        arguments:
          artifacts:
          - {name: gene-classifier-model-training-model_path, from: '{{tasks.gene-classifier-model-training.outputs.artifacts.gene-classifier-model-training-model_path}}'}
          - {name: gene-classifier-test-dataset-generation-csv_path, from: '{{tasks.gene-classifier-test-dataset-generation.outputs.artifacts.gene-classifier-test-dataset-generation-csv_path}}'}
      - name: gene-classifier-model-training
        template: gene-classifier-model-training
        dependencies: [gene-classifier-train-dataset-generation, gene-classifier-validation-dataset-generation]
        arguments:
          artifacts:
          - {name: gene-classifier-train-dataset-generation-csv_path, from: '{{tasks.gene-classifier-train-dataset-generation.outputs.artifacts.gene-classifier-train-dataset-generation-csv_path}}'}
          - {name: gene-classifier-validation-dataset-generation-csv_path, from: '{{tasks.gene-classifier-validation-dataset-generation.outputs.artifacts.gene-classifier-validation-dataset-generation-csv_path}}'}
      - {name: gene-classifier-test-dataset-generation, template: gene-classifier-test-dataset-generation}
      - {name: gene-classifier-train-dataset-generation, template: gene-classifier-train-dataset-generation}
      - {name: gene-classifier-validation-dataset-generation, template: gene-classifier-validation-dataset-generation}
  - name: gene-classifier-model-testing
    container:
      args: []
      command: [python3.9, gc_handler.py, -test_csv_path, /tmp/inputs/test_csv_path/data,
        -model_path, /tmp/inputs/model_path/data, -results_path, /tmp/outputs/results_path/data]
      image: localhost:5001/step-model-config:latest
      resources:
        limits: {nvidia.com/gpu: 1}
    inputs:
      artifacts:
      - {name: gene-classifier-model-training-model_path, path: /tmp/inputs/model_path/data}
      - {name: gene-classifier-test-dataset-generation-csv_path, path: /tmp/inputs/test_csv_path/data}
    outputs:
      artifacts:
      - {name: gene-classifier-model-testing-results_path, path: /tmp/outputs/results_path/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Effettua
          il testing del modello GC", "implementation": {"container": {"command":
          ["python3.9", "gc_handler.py", "-test_csv_path", {"inputPath": "test_csv_path"},
          "-model_path", {"inputPath": "model_path"}, "-results_path", {"outputPath":
          "results_path"}], "image": "localhost:5001/step-model-config:latest"}},
          "inputs": [{"description": "Test CSV path.", "name": "test_csv_path", "type":
          "String"}, {"description": "H5 Model path.", "name": "model_path", "type":
          "String"}], "name": "Gene Classifier Model Testing", "outputs": [{"description":
          "CSV results path.", "name": "results_path", "type": "String"}]}', pipelines.kubeflow.org/component_ref: '{"digest":
          "966865715dce86294753bad02925485561862d2a6fdf841db73ff2d008729b24", "url":
          "kube-pipe/components/gene-classifier/model/test/component.yaml"}'}
  - name: gene-classifier-model-training
    container:
      args: []
      command: [python3.9, gc_handler.py, -train_csv_path, /tmp/inputs/train_csv_path/data,
        -val_csv_path, /tmp/inputs/val_csv_path/data, -model_path, /tmp/outputs/model_path/data]
      image: localhost:5001/step-model-config:latest
      resources:
        limits: {nvidia.com/gpu: 1}
    inputs:
      artifacts:
      - {name: gene-classifier-train-dataset-generation-csv_path, path: /tmp/inputs/train_csv_path/data}
      - {name: gene-classifier-validation-dataset-generation-csv_path, path: /tmp/inputs/val_csv_path/data}
    outputs:
      artifacts:
      - {name: gene-classifier-model-training-model_path, path: /tmp/outputs/model_path/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Effettua
          l''addestramento del modello GC", "implementation": {"container": {"command":
          ["python3.9", "gc_handler.py", "-train_csv_path", {"inputPath": "train_csv_path"},
          "-val_csv_path", {"inputPath": "val_csv_path"}, "-model_path", {"outputPath":
          "model_path"}], "image": "localhost:5001/step-model-config:latest"}}, "inputs":
          [{"description": "Training CSV path.", "name": "train_csv_path", "type":
          "String"}, {"description": "Validation CSV path.", "name": "val_csv_path",
          "type": "String"}], "name": "Gene Classifier Model Training", "outputs":
          [{"description": "H5 Model path.", "name": "model_path", "type": "String"}]}',
        pipelines.kubeflow.org/component_ref: '{"digest": "1513e7e5e499c56cb389129f278839ed4adb42c2d9503f904e09d62cb427469e",
          "url": "kube-pipe/components/gene-classifier/model/train/component.yaml"}'}
  - name: gene-classifier-test-dataset-generation
    container:
      args: []
      command: [python, gc_handler.py, -type, test, -csv_path, /tmp/outputs/csv_path/data]
      image: localhost:5001/step-dataset-generation-config:latest
    outputs:
      artifacts:
      - {name: gene-classifier-test-dataset-generation-csv_path, path: /tmp/outputs/csv_path/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Genera
          il dataset di testing del modello GC", "implementation": {"container": {"command":
          ["python", "gc_handler.py", "-type", "test", "-csv_path", {"outputPath":
          "csv_path"}], "image": "localhost:5001/step-dataset-generation-config:latest"}},
          "name": "Gene Classifier Test Dataset Generation", "outputs": [{"description":
          "Test CSV path.", "name": "csv_path", "type": "String"}]}', pipelines.kubeflow.org/component_ref: '{"digest":
          "a7695b36e5acc809a8aff9e544ab9c4ec26d684a1e8506c48dbb1f608b295a39", "url":
          "kube-pipe/components/gene-classifier/dataset/test/component.yaml"}'}
  - name: gene-classifier-train-dataset-generation
    container:
      args: []
      command: [python, gc_handler.py, -type, train, -csv_path, /tmp/outputs/csv_path/data]
      image: localhost:5001/step-dataset-generation-config:latest
    outputs:
      artifacts:
      - {name: gene-classifier-train-dataset-generation-csv_path, path: /tmp/outputs/csv_path/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Genera
          il dataset di training del modello GC", "implementation": {"container":
          {"command": ["python", "gc_handler.py", "-type", "train", "-csv_path", {"outputPath":
          "csv_path"}], "image": "localhost:5001/step-dataset-generation-config:latest"}},
          "name": "Gene Classifier Train Dataset Generation", "outputs": [{"description":
          "Train CSV path.", "name": "csv_path", "type": "String"}]}', pipelines.kubeflow.org/component_ref: '{"digest":
          "20f9496750b4a6d86f25998527fb11347eaf81fb3b16339c4a204fd76290b3c5", "url":
          "kube-pipe/components/gene-classifier/dataset/train/component.yaml"}'}
  - name: gene-classifier-validation-dataset-generation
    container:
      args: []
      command: [python, gc_handler.py, -type, val, -csv_path, /tmp/outputs/csv_path/data]
      image: localhost:5001/step-dataset-generation-config:latest
    outputs:
      artifacts:
      - {name: gene-classifier-validation-dataset-generation-csv_path, path: /tmp/outputs/csv_path/data}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Genera
          il dataset di validazione del modello GC", "implementation": {"container":
          {"command": ["python", "gc_handler.py", "-type", "val", "-csv_path", {"outputPath":
          "csv_path"}], "image": "localhost:5001/step-dataset-generation-config:latest"}},
          "name": "Gene Classifier Validation Dataset Generation", "outputs": [{"description":
          "Validation CSV path.", "name": "csv_path", "type": "String"}]}', pipelines.kubeflow.org/component_ref: '{"digest":
          "df86f828c0e92f2805eeef75b8ba2a1b13df1604b18a4129818f9f5d420348f0", "url":
          "kube-pipe/components/gene-classifier/dataset/val/component.yaml"}'}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
